@ECHO OFF

SET PVM_TEMPFILE=%TEMP%\PVM-TEMP-%DATE%-%RANDOM%.TMP

PathVariableManager.exe %1 %2 %3 %4

:: 
IF %ERRORLEVEL% == 9 (
	SET /P PATH= < %PVM_TEMPFILE%
)

IF EXIST %PVM_TEMPFILE% (
	DEL %PVM_TEMPFILE%
)
SET PVM_TEMPFILE=